[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.8
padding.x = 10
padding.y = 10
option_as_alt = "Both"

[font]
normal = { family = "Comic Code", style = "Regular" }
size = 14.0

[selection]
save_to_clipboard = true
